# main menu
[[main]]
name = "Home"
url = ""
weight = 1

# TODO fill out about page
#[[main]]
#name = "About"
#url = "about/"
#weight = 2

[[main]]
weight = 2
name = "Services"
hasChildren = true

  [[main]]
  parent = "Services"
  name = "Web Security Assessments"
  url = "web_security_assessments/"
  weight = 1

  [[main]]
  parent = "Services"
  name = "Cloud Security Review"
  url = "cloud-security-review/"
  weight = 2

  [[main]]
  parent = "Services"
  name = "Social Engineering"
  url = "social-engineering-penetration-tests/"
  weight = 2

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 3


#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

  #[[main]]
  #parent = "Pages"
  #name = "Blog Details"
  #url = "blog/post-1/"
  #weight = 1

  #[[main]]
  #parent = "Pages"
  #name = "Terms & Conditions"
  #url = "terms-and-conditions/"
  #weight = 7
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5

#[[main]]
#name = "Example"
#url = "example/"
#weight = 5


# footer menu
[[footer]]
name = "Cloud Security Review"
url = "cloud-security-review/"
weight = 1

[[footer]]
name = "Web Security Assessments"
url = "web_security_assessments/"
weight = 2

[[footer]]
name = "Social Engineering Services"
url = "social-engineering-penetration-tests/"
weight = 3

