#################### default parameters ################################
# favicon
favicon = "images/rbs-favicon.png"
# logo
#logo = "images/logo.svg"
logo = "images/rbs-logo-cropped.png"
# use `x` with logo_width, example: "100x"
logo_width = "120x"
# logo text will only show when logo is missing.
logo_text = "Red Bell Security"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Red Bell Security"
#image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own
image = "images/rbs-logo.png"

# footer information
#footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://share.hsforms.com/1N4UsB4enRfCFZtUtL9qFDgd3fh3" # contact form works with https://formspree.io # To change this to work with Hubspot, modify the layouts/_default/contact.html file within the andromeda-light directory

# copyright
copyright = "Designed By Red Bell Security"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Denver, Colorado & Madison, WI"
phone = [""]
email = [""]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Contact Us"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Get in Touch"
content = ""
button = "Contact Us"
#button_link = "https://gethugothemes.com/products/andromeda/"
button_link = "contact/"

############################# social site ########################
[[social]]
title = "Andromeda"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "AndromedaTweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "AndromedaIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "AndromedaPin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
